name: "Tools - Validate JSON Schema"

on:
  push:
    branches: [ "customize" ]
  pull_request:
    branches: [ "customize" ]


jobs:
  validate-json-schema:
    name: Validate JSON Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
